[versions]
okhttp4 = "4.9.2"

[libraries]
interceptor-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp4" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp4" }
